security:
    providers:
        users:
            entity: { class: App\Entity\User, property: username }
        admin:
            entity: { class: App\Entity\Admin, property: username }

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            memory_cost: 16384
            time_cost: 2
            threads: 4
        App\Entity\Admin:
            algorithm: bcrypt
            memory_cost: 16384
            time_cost: 2
            threads: 4

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/_easyadmin
            provider: admin
            anonymous: ~
            logout:
                invalidate_session: true
                path: /_easyadmin/logout
                target: /
            guard:
                authenticators:
                    - App\Security\Guard\AdminAuthenticator
        middle:
            pattern: ^/(cssr|api)
            provider: users
            anonymous: ~
            logout:
                invalidate_session: true
                path: /cssr/logout
                target: /cssr
            guard:
                authenticators:
                    - App\Security\Guard\UserAuthenticator

    access_control:
        - { path: ^/_easyadmin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_easyadmin, role: ROLE_SUPER_ADMIN }
        - { path: ^/cssr/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cssr/password/request$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cssr/password/reset/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cssr, roles: [ROLE_SMP, ROLE_CSSR, ROLE_CONSULTANT] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
