parameters:
    app.path.testimonial_image: /uploads/testimonial
    app.path.page_image: /uploads/page
    app.path.article: /uploads/article
    app.path.snippet: /uploads/snippet

vich_uploader:
    db_driver: orm

    mappings:
        testimonial:
            uri_prefix: '%app.path.testimonial_image%'
            upload_destination: '%kernel.project_dir%/public/uploads/testimonial'
        page:
            uri_prefix: '%app.path.page_image%'
            upload_destination: '%kernel.project_dir%/public/uploads/page'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        article:
            uri_prefix: '%app.path.article%'
            upload_destination: '%kernel.project_dir%/public/uploads/article'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        snippet:
            uri_prefix: '%app.path.snippet%'
            upload_destination: '%kernel.project_dir%/public/uploads/snippet'